[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["node", "python"]

[build.nixpacks.phases.setup]
nixPkgs = ["python3", "nodejs_20"]

[build.nixpacks.phases.install]
dependsOn = ["setup"]
cmds = ["npm install --prefix frontend", "pip install -r backend/requirements.txt"]

[build.nixpacks.phases.build]
dependsOn = ["install"]
cmds = ["npm run build --prefix frontend"]

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
